theme: jekyll-theme-minimal
title: Feng Cheng's Homepage
# logo: 
# description: Undergraduate Student in Mathematics and Statistics at UC Berkeley
author:
  name: "Cheng, Feng"
  bio: "Senior at University of California, Berkeley"
  location: "San Francisco Bay Area, USA / Shanghai, China"
  # avatar: 
  github: "fredcheng02"
